updated env file generation and variable getting via ssm

diff --git a/.github/workflows/build_android.yml b/.github/workflows/build_android.yml
--- a/.github/workflows/build_android.yml
+++ b/.github/workflows/build_android.yml
@@ -18,8 +18,6 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-        with:
-          repository: ${{ inputs.repository }}
 
       - name: Get Version
         run: |
@@ -29,12 +27,12 @@ jobs:
           echo "app_build_name=$app_build_name" >> $GITHUB_ENV
 
       - name: Setup Java Version
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v4        # era v1
         with:
-          java-version: "12.x"
+          java-version: "17"               # era 12, Flutter 3.24 exige 17+
 
       - name: Setup Flutter Version
-        uses: subosito/flutter-action@v1
+        uses: subosito/flutter-action@v2   # era v1
         with:
           flutter-version: "3.24.3"
 
@@ -47,6 +45,26 @@ jobs:
           ruby-version: "2.6"
           bundler-cache: true
           working-directory: android
+
+      - name: Set AWS Account ID and other variables
+        run: |
+          if [[ "${{ github.ref_name }}" == "dev" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOML }}" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+            echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name!" && exit 1
+          fi
+          echo "STACK_NAME=DevMediasStack${{github.ref_name}}" >> $GITHUB_ENV
+  
+      - name: Setup AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ vars.AWS_REGION }}
+          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+          role-session-name: github-action
 
       - name: Set envs
         run: |
@@ -65,23 +83,50 @@ jobs:
           ANDROID_KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}
         working-directory: android
 
+      # esse processo busca o endpoint do APIGW direto da variável setada pelo SSM configurado no back
+      # evitando essa passagem manual dessa endpoint pro secrets do github e evitando possíveis erros
+      # de passagem manual
+
+      - name: Fetch config from SSM
+        run: |
+          STAGE=dev
+
+          API_BASE=$(aws ssm get-parameter \
+            --name "/devmedias/$STAGE/api/url" \
+            --query "Parameter.Value" --output text)
+
+          CDN_PLANS=$(aws ssm get-parameter \
+            --name "/devmedias/$STAGE/cdn/plans" \
+            --query "Parameter.Value" --output text)
+
+          CDN_SUBJECTS=$(aws ssm get-parameter \
+            --name "/devmedias/$STAGE/cdn/subjects" \
+            --query "Parameter.Value" --output text)
+
+          echo "API_BASE=$API_BASE" >> $GITHUB_ENV
+          echo "CDN_SUBJECTS=$CDN_SUBJECTS" >> $GITHUB_ENV
+
       - name: Create .env file
         run: |
-          echo "API_COURSES=${{vars.API_COURSES}}" >> .env # The courses API
-          echo "API_SUBJECTS=${{vars.API_SUBJECTS}}" >> .env # The subjects API
-          echo "API_GRADE_OPTMIZER=${{vars.API_GRADE_OPTMIZER}}" >> .env # The grade optimizer API
-          echo "API_SUPPORT_URL=${{vars.API_SUPPORT_URL}}" >> .env # The support API
-          echo "API_FINAL_SCORE_URL=${{vars.API_FINAL_SCORE_URL}}" >> .env # The final score API
+          echo "API_COURSES=https://$CDN_SUBJECTS/courses.json" >> .env
+          echo "API_SUBJECTS=https://$CDN_SUBJECTS/allSubjects.json" >> .env
+          echo "API_GRADE_OPTMIZER=${API_BASE}grade-optmizer" >> .env
+          echo "API_GENETIC_ALGORITHM=${API_BASE}genetic-algorithm" >> .env
+          echo "API_SUPPORT_URL=${API_BASE}public/contact-us" >> .env
+          echo "API_FINAL_SCORE_URL=${API_BASE}calculate-mean" >> .env
 
       - name: Build Android
         run: |
-          flutter build appbundle --release --build-name=$app_build_name --build-number=$app_build_number
-
+          flutter build appbundle --release \
+            --build-name=$app_build_name \
+            --build-number=$app_build_number
+    
       - name: Upload to artifacts
         uses: actions/upload-artifact@v4
         with:
           name: app-release.aab
           path: build/app/outputs/bundle/release/
+          retention-days: 1 
 
   deploy_to_play_store:
     needs: build_android
@@ -102,12 +147,12 @@ jobs:
       - name: Setup Fastlane
         uses: ruby/setup-ruby@v1
         with:
-          ruby-version: "2.6"
+          ruby-version: "3.2"
           bundler-cache: true
           working-directory: android
 
       - name: Exec fastlane
-        run: bundle exec fastlane ${{github.ref_name}}
+        run: bundle exec fastlane ${{ github.ref_name }}
         env:
           PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
         working-directory: android
